apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-installer-config
  namespace: wazuh
data:
  install.sh: |
    #/bin/bash
    apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    ca-certificates && \
    # Download and install specific Wazuh agent package
    curl -s -o wazuh-agent_4.12.0-1_amd64.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.12.0-1_amd64.deb && \
    dpkg -i wazuh-agent_4.12.0-1_amd64.deb || apt-get install -f -y

    echo "copying ossec files"
    cp /var/ossec.conf  /var/ossec/etc/
    cp /var/authd.pass /var/ossec/etc/

    # Register agent with manager
    /var/ossec/bin/agent-auth -m  <Wazuh Manager IP>
    # Reload systemd and start services
    /var/ossec/bin/wazuh-control start
    /var/ossec/bin/wazuh-control restart

