apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-installer-config
  namespace: wazuh
data:
  install.sh: |
    #!/bin/bash

    set -e

    echo "[*] Fixing interrupted dpkg if any..."
    dpkg --configure -a || true

    echo "[*] Updating packages and installing dependencies..."
    apt-get update && \
    apt-get install -y --no-install-recommends \
      gnupg \
      curl \
      ca-certificates

    echo "[*] Adding Wazuh GPG key and repository..."
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
      gpg --no-default-keyring --keyring /usr/share/keyrings/wazuh.gpg --import
    chmod 644 /usr/share/keyrings/wazuh.gpg

    echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" \
      > /etc/apt/sources.list.d/wazuh.list

    echo "[*] Installing wazuh-agent..."
    apt-get update
    apt-get install -y wazuh-agent

    # Validate installation
    if [ ! -d "/var/ossec" ]; then
      echo "ERROR: /var/ossec directory not found. Agent may not be installed."
      exit 1
    fi

    echo "[*] Copying ossec configuration..."
    cp /var/ossec.conf /var/authd.pass /var/ossec/etc/

    echo "[*] Registering agent with Wazuh manager..."
    /var/ossec/bin/agent-auth -m $MANAGER-IP

    echo "[*] Restarting Wazuh agent..."
    /host/ossec/bin/wazuh-control restart

    echo "[*] Disabling automatic upgrades..."
    sed -i 's/^deb/#deb/' /etc/apt/sources.list.d/wazuh.list

    echo "[*] Checking agent status..."
    /host/ossec/bin/wazuh-control status

    echo "[*] Installation complete."
